seo:
  site_name: 
  title:
  type: website
  description: 
  keywords: 
  social_image:
  author: 
  twitter_description: 
social:
  instagram_username: 
  facebook_username:
  pinterest_username:
  linkedin_username:
  twitter_username: 
  tiktok_username: 
  youtube_username:
brand:
  primary_color: '#E5E0D3'
  secondary_color: '#C7B9A3'
  light_color: '#F1EDE6'
  dark_color: '#231F20'
  bright_color: '#C98665'
  primary_logo_path: /images/swatch-architects-bali-logo-primary.png
  secondary_logo_path: 
  submark_logo_path:
technical:
  google-analytics_embed:
  instagram_widget_embed:
  code_for_head: